[project]
name = "finance-resampler"
version = "0.1.0"
authors = [
    { name = "raccoon00", email = "vladimir.chekmenyov1@yandex.ru" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.9,<0.10.0"]
build-backend = "uv_build"
